//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste_tecnico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_documentos
    {
        public int codigo { get; set; }
        public string titulo { get; set; }
        public string processo { get; set; }
        public string categoria { get; set; }
        public string arquivo { get; set; }
    }
}
